### ISSUE TITLE
Crash on Huawei p10 on RR 8.1 with magisk

### ISSUE THREAD

**Issue by Kemoke** [james34602/JamesDSPManager#17]
App crashes on start.
Installed through magisk manager.

08-28 23:37:18.582 3518-3518/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: james.dsp, PID: 3518
    java.lang.RuntimeException: Unable to create service james.dsp.service.HeadsetService: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3350)
        at android.app.ActivityThread.-wrap4(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1678)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6499)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at james.dsp.service.HeadsetService$JDSPModule.<init>(HeadsetService.java:73)
        at james.dsp.service.HeadsetService.onCreate(HeadsetService.java:459)
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3340)
        at android.app.ActivityThread.-wrap4(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1678) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6499) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
        at james.dsp.service.HeadsetService$JDSPModule.<init>(HeadsetService.java:68)
        at james.dsp.service.HeadsetService.onCreate(HeadsetService.java:459) 
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3340) 
        at android.app.ActivityThread.-wrap4(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1678) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6499) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
     **Caused by: java.lang.RuntimeException: Cannot initialize effect engine for type: f98765f4-c321-5de6-9a45-123459495ab2 Error: -3**
        at android.media.audiofx.AudioEffect.<init>(AudioEffect.java:411)
        at java.lang.reflect.Constructor.newInstance0(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:334) 
        at james.dsp.service.HeadsetService$JDSPModule.<init>(HeadsetService.java:68) 
        at james.dsp.service.HeadsetService.onCreate(HeadsetService.java:459) 
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3340) 
        at android.app.ActivityThread.-wrap4(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1678) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6499) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by james34602** [comment]
Some user report it is required to install V4A after JDSP, to get JDSP working.
Also, you need to receive patches for new Android audio framework fix from:
[JDSP and V4A group](https://t.me/jDSP_V4A)

**Comment by james34602** [comment]
It have been solved via arm64 binary of libjamesdsp.so
Again:
Join JDSP and V4A group in Telegram to receive latest news
